alias kek='source ~/workspace/set_environment_stuff_to_newest_gcc_and_ccls.sh && ~/workspace/kakoune/src/kak'
alias serv='ssh serv@h2054422.stratoserver.net'
#alias c2v='source ~/workspace/c2v/set_environment_stuff_for_c2v.sh && ~/workspace/c2v/c2v'
alias uacme='~/workspace/uacme/uacme'
alias muacme='~/workspace/muacme-0.5.1/muacme'
alias vab='source ~/workspace/set_environment_stuff_for_vab.sh && vab'
alias androidstudio='~/workspace/android-studio/bin/studio.sh'
alias youtube-dl='~/.local/bin/youtube-dl'
alias yt-dlp='~/workspace/yt-dlp/yt-dlp.sh'
alias meson='~/workspace/meson/meson.py'
alias ga="cd ~/workspace/adk/AntonsDungeonKeeper/"
alias gw="cd ~/workspace"
alias go="cd ~/workspace/OpenDungeons"
alias gc="cd ~/Configs"
alias gg="cd ~/Documents/bundesministerium_der_justitz/"
alias gn="cd ~/workspace/neural/"
alias gv="cd ~/workspace/Vulkan/"
alias gp="cd ~/workspace/planisphere/"
alias gf="cd ~/workspace/FTXUI/"
alias lbrynet="source ~/workspace/lbry-sdk/lbry-venv/bin/activate && ~/workspace//lbry-sdk/lbry-venv/bin/lbrynet"
